/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/login/number-code copy.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    NumberCode: typeof import('./src/components/login/number-code.vue')['default']
    OtpVerification: typeof import('./src/components/login/otp-verification.vue')['default']
    OtpVerificationForm: typeof import('./src/components/login/otp-verification-form.vue')['default']
    PhoneNumberForm: typeof import('./src/components/login/phone-number-form.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanInput: typeof import('vant/es')['Input']
    VanSearch: typeof import('vant/es')['Search']
  }
}
