/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FactoryPicker: typeof import('./src/components/top-bar/factory-picker.vue')['default']
    LoginForm: typeof import('./src/components/login/login-form.vue')['default']
    OrderCard: typeof import('./src/components/order/order-card.vue')['default']
    OrderList: typeof import('./src/components/order/order-list.vue')['default']
    OtpVerificationForm: typeof import('./src/components/login/otp-verification-form.vue')['default']
    PhoneNumberForm: typeof import('./src/components/login/phone-number-form.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/top-bar/search-bar.vue')['default']
    TopBar: typeof import('./src/components/top-bar/topBar.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanDivider: typeof import('vant/es')['Divider']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanHighlight: typeof import('vant/es')['Highlight']
    VanIcon: typeof import('vant/es')['Icon']
    VanLink: typeof import('vant/es')['Link']
    VanList: typeof import('vant/es')['List']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
  }
}
